BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task.yaml
TRAINER_NAME: dagger # recollect_trainer
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 10
TENSORBOARD_DIR: data/tensorboard_dirs/seq2seq_small
CHECKPOINT_FOLDER: data/checkpoints/seq2seq_small
EVAL_CKPT_PATH_DIR: data/checkpoints/seq2seq_small
RESULTS_DIR: data/checkpoints/seq2seq_small/evals


EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: -1

IL:
  epochs: 15
  batch_size: 5
  

  RECOLLECT_TRAINER:
    gt_file:
      data/datasets/annt/{split}/{split}_gt.json.gz

  DAGGER:
    iterations: 20
    update_size: 10000
    p: 1.0
    preload_lmdb_features: False
    lmdb_features_dir: data/trajectories_dirs/seq2seq_small/tra

MODEL:
  policy_name: Seq2SeqPolicy